Delete .htaccess because it causes http 500 errors for each file:
NetworkError: 500 Internal Server Error - http://localhost/ow_cubeviz/extensions/cubeviz/static/javascript/libraries/highcharts/highcharts.js
NetworkError: 500 Internal Server Error - http://localhost/ow_cubeviz/extensions/cubeviz/static/javascript/libraries/json2.js
...